menubar:
  - false
toolbar:
  - undo redo | styleselect | bold italic backcolor | alignleft aligncenter alignright | bullist numlist outdent indent | image | link | table | code | help
  - emoticons | insertdatetime |
contextmenu:
  'link image table'
plugins:
  - image
  - link
  - table
  - lists
  - searchreplace
  - visualblocks
  - code
  - fullscreen
  - insertdatetime
  - media
  - paste
  - help
  - wordcount
  - autolink
  - imagetools
  - emoticons


